# Generated by Django 4.2.1 on 2023-05-21 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Название категории',
                        max_length=150,
                        verbose_name='название',
                    ),
                ),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Имя продукта',
                        max_length=150,
                        verbose_name='имя',
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        help_text='Описание продукта', verbose_name='описание'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='Время создания продукта',
                        verbose_name='время создания',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text='Время обновления продукта',
                        verbose_name='время обновления',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True,
                        help_text='Опубликован продукт или нет',
                        verbose_name='опубликован',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        help_text='Категория, к которой относится продукт',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='products.category',
                        verbose_name='категория',
                    ),
                ),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
